version: '3'

services:
  # nginx服务，提供静态网站和视频
  nginx:
    ports:
      - "8090:80"  # 将容器内的80端口映射到主机的8090端口
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # 挂载Nginx配置
      - ./dist:/opt/dist  # 挂载构建后的Vue应用
      - ./videos:/opt/videos  # 挂载视频文件目录
    environment:
      - TZ=Asia/Shanghai  # 设置时区
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3" 